### ISSUE TITLE
404 after starting

### ISSUE THREAD

**Issue by leopku** [kyicy/readimension#2]
1. make all
2. visit http://host:10086

Browser was redirected to `/u/explorer/1` and report "not found".

Could you give some help?

**Comment by kyicy** [comment]
Hi @leopku 
Sorry for the late response.
Initially, you have to go to `/sign-up` to register yourself as an administrator.
I've made several  changes to fix this issue.
Please update the codebase and try again.

**Comment by leopku** [comment]
It works.
Big thanks.
