### ISSUE TITLE
Could add support for docker?

### ISSUE THREAD

**Issue by wswv** [kyicy/readimension#3]
Hi, I reviewed the demo the software, I think it good!

Does it possible to add docker for it?

The docker is easy to implement software for us, so if could add the function for it, it will benefit for somebody who want to implement it. 

Thanks!

**Comment by kyicy** [comment]
Apologies for the delayed response.

I've added a simple `Dockerfile` in the root directory.

Check the readme: https://github.com/kyicy/readimension#docker-usage
